---
steps:
  - name: python:3.9-alpine
    id: Unit Tests
    entrypoint: sh
    args:
      - -c
      - |
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
        python -m pytest -W ignore::DeprecationWarning -v
